import test from 'node:test';
import assert from 'node:assert/strict';
import { edgeAvailable, launchBrowser } from './helpers/browser-harness.mjs';
import { createSmokeServer } from './helpers/smoke-server.mjs';

test('共享玻璃表面覆盖静态动态浮层，嵌套仅保留最上层遮罩', { timeout: 40000 }, async (t) => {
  if (!edgeAvailable()) return t.skip('未安装 Edge');
  const fixture = await createSmokeServer();
  const browser = await launchBrowser({ width: 1440, height: 900 });
  t.after(async () => { await browser.close(); await fixture.close(); });
  const inspect = async (selector) => JSON.parse(await browser.evaluate(`JSON.stringify((() => {
    const n=document.querySelector(${JSON.stringify(selector)}), s=getComputedStyle(n), r=n.getBoundingClientRect();
    return { kind:n.dataset.glassSurface, background:s.backgroundColor, filter:s.backdropFilter, shadow:s.boxShadow, opacity:s.opacity, width:r.width, inside:r.left>=0 && r.right<=innerWidth+1 && r.top>=0 && r.bottom<=innerHeight+1 };
  })())`));
  const glass = async (selector, kind) => {
    const s = await inspect(selector);
    assert.equal(s.kind, kind);
    assert.equal(s.opacity, '1');
    assert.equal(s.background, 'rgba(255, 255, 255, 0.35)');
    assert.ok(s.filter.includes('20px'));
    assert.notEqual(s.shadow, 'none');
    assert.ok(s.inside, JSON.stringify(s));
  };
  const base = `http://127.0.0.1:${fixture.port}`;
  await browser.navigate(base + '/');
  await browser.waitFor("document.documentElement.classList.contains('app-ready')");
  await browser.evaluate('newTaskButton.click()');
  await browser.waitFor("taskModal.dataset.glassShade === 'active'");
  await glass('#taskForm', 'large');
  assert.equal(await browser.evaluate("getComputedStyle(taskModal).backdropFilter"), 'none');
  await browser.evaluate('taskPlannedDate.click()');
  await glass('#taskDatePicker', 'small');
  await browser.evaluate('cancelTaskButton.click(); openChatHistoryButton.click()');
  await glass('#chatHistoryDrawer', 'large');
  await browser.evaluate('closeChatHistoryButton.click(); directoryButton.click()');
  await glass('#conversationDirectory', 'small');
  assert.equal(await browser.evaluate("getComputedStyle(document.querySelector('.calendar-panel')).backdropFilter"), 'none');
  await browser.evaluate("directoryButton.click(); workspaceSwitcher.click()");
  await browser.waitFor("document.querySelector('.workspace-switcher-dialog')?.dataset.glassShade === 'active'");
  await glass('.workspace-switcher-dialog', 'large');
  await browser.evaluate("document.querySelector('.workspace-switcher-dialog').close()");
  await browser.evaluate('taskSummaryDialog.showModal()');
  await browser.waitFor("taskSummaryDialog.dataset.glassShade === 'active'");
  const preview = await inspect('#taskSummaryDialog');
  assert.equal(preview.background, 'rgba(255, 255, 255, 0.35)');
  assert.ok(preview.filter.includes('20px'));
  assert.equal(await browser.evaluate("getComputedStyle(taskSummaryDialog,'::backdrop').backgroundColor"), 'rgba(10, 10, 10, 0.08)');
  assert.equal(await browser.evaluate("getComputedStyle(taskSummaryDialog.querySelector('header')).backgroundColor"), 'rgba(255, 255, 255, 0.12)');
  await browser.evaluate('taskSummaryDialog.close()');
  await browser.navigate(base + '/assistant.html');
  await browser.waitFor("modelPickerButton.textContent.includes('GPT Test')");
  await browser.evaluate('modelPickerButton.click()');
  await glass('#modelPickerPanel', 'small');
  await browser.evaluate("modelPickerPanel.classList.add('hidden'); settingsButton.click()");
  await browser.waitFor("settingsDialog.dataset.glassShade === 'active'");
  await glass('#settingsDialog', 'large');
  assert.equal(await browser.evaluate('getComputedStyle(settingsDialog).fontSize'), '13px');
  assert.equal(await browser.evaluate('getComputedStyle(closeSettings).width'), '32px');
  assert.equal(await browser.evaluate("getComputedStyle(settingsDialog.querySelector('.settings-tabs button')).fontSize"), '13px');
  await browser.evaluate(`document.querySelector('[data-settings-tab="skills"]').click()`);
  await browser.waitFor("skillsTab.classList.contains('active') && skillsList.textContent !== '正在读取……'");
  await browser.evaluate("skillDiagnosticsBox.classList.remove('hidden'); skillDiagnosticsBox.open=true; skillDiagnostics.textContent='重复名称诊断\\n'.repeat(20)");
  assert.equal(await browser.evaluate("(() => { const box=skillDiagnosticsBox.getBoundingClientRect(), tab=skillsTab.getBoundingClientRect(), list=document.querySelector('.skills-layout').getBoundingClientRect(); return box.bottom<=tab.bottom+1 && box.top>=list.bottom && box.height>30; })()"), true);
  await browser.evaluate('secretDialog.showModal()');
  await browser.waitFor("secretDialog.dataset.glassShade === 'active' && settingsDialog.dataset.glassShade === 'inactive'");
  assert.equal(await browser.evaluate("getComputedStyle(settingsDialog,'::backdrop').backgroundColor"), 'rgba(0, 0, 0, 0)');
  assert.equal(await browser.evaluate("getComputedStyle(secretDialog,'::backdrop').backgroundColor"), 'rgba(10, 10, 10, 0.08)');
  await glass('#secretDialog', 'large');
  await browser.evaluate('uiDialog.showModal()');
  await browser.waitFor("uiDialog.dataset.glassShade === 'active' && secretDialog.dataset.glassShade === 'inactive'");
  await browser.evaluate('uiDialog.close(); secretDialog.close()');
  await browser.waitFor("settingsDialog.dataset.glassShade === 'active'");
  await browser.evaluate('closeSettings.click(); showWorkspace.click(); directoryButton.click()');
  await glass('#conversationDirectory', 'small');
  // Unknown/native surfaces must not be styled just because they are dialogs.
  await browser.evaluate("const unrelated=document.createElement('dialog');unrelated.id='unrelated';document.body.append(unrelated)");
  assert.equal(await browser.evaluate("unrelated.hasAttribute('data-glass-surface')"), false);
});
