import test from 'node:test';
import assert from 'node:assert/strict';
import { edgeAvailable, launchBrowser } from './helpers/browser-harness.mjs';
import { createSmokeServer } from './helpers/smoke-server.mjs';

test('持续事项排序记忆、日期独立、编辑保位、弹窗滚动及圆形新建入口', {timeout:35000}, async t => {
  if (!edgeAvailable()) return t.skip('需要Edge');
  const fixture=await createSmokeServer(); let browser;
  t.after(async()=>{try{await browser?.close();}finally{await fixture.close();}});
  fixture.state.tasks=Array.from({length:18},(_,i)=>({id:`long-${i}`,kind:'longterm',text:`持续事项${i}`,editableText:`持续事项${i}`,checked:false,startDate:'2026-09-04',headingPath:['持续工作'],sourceLine:i+1}));
  const original=structuredClone(fixture.state.tasks);
  browser=await launchBrowser({width:1440,height:900});
  const url=`http://127.0.0.1:${fixture.port}/`;
  const open=async()=>{await browser.navigate(url);await browser.waitFor("document.documentElement.classList.contains('app-ready') && longtermCount.textContent==='18'");await browser.evaluate("calendarGrid.querySelector('[data-date=\"2026-09-04\"]').click()");await browser.waitFor("dayTasks.querySelector('.task-card')");await browser.evaluate('openLongtermTasks.click()');};
  const titles=()=>browser.evaluate("[...longtermTasks.querySelectorAll('.task-card-title')].map(n=>n.textContent)");
  await open();
  await browser.waitFor("dayTasks.querySelector('.task-card')");
  const cardStyles = await browser.evaluate("[dayTasks,longtermTasks].map(list=>{const s=getComputedStyle(list.querySelector('.task-card'));return [s.backgroundColor,s.padding,s.rowGap,s.borderRadius,s.transition,s.cursor,s.userSelect]})");
  assert.deepEqual(cardStyles[1],cardStyles[0]);
  assert.equal(await browser.evaluate("longtermTasks.querySelectorAll('[draggable=true]').length"),18);
  assert.deepEqual(await browser.evaluate("[newLongtermTaskButton,newTaskButton].map(e=>{const r=e.getBoundingClientRect();return [r.width,r.height,getComputedStyle(e).borderRadius,!!e.querySelector('use[href=\"/icons.svg#plus\"]')]})"), [[36,36,'9999px',true],[36,36,'9999px',true]]);
  await browser.evaluate(`(()=>{const s=longtermTasks.children[2],t=longtermTasks.children[0],dt=new DataTransfer(),y=t.getBoundingClientRect().top+2;s.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));s.dispatchEvent(new DragEvent('dragstart',{bubbles:true,cancelable:true,dataTransfer:dt}));t.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt,clientY:y}));t.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt,clientY:y}));s.dispatchEvent(new DragEvent('dragend',{bubbles:true,dataTransfer:dt}));})()`);
  assert.deepEqual((await titles()).slice(0,3),['持续事项2','持续事项0','持续事项1']);
  const dragStyles=await browser.evaluate(`(async()=>{const s=longtermTasks.children[1],t=longtermTasks.children[0],dt=new DataTransfer(),box=t.getBoundingClientRect();s.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));s.dispatchEvent(new DragEvent('dragstart',{bubbles:true,cancelable:true,dataTransfer:dt}));t.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt,clientY:box.top+2}));await new Promise(r=>setTimeout(r,200));const before=getComputedStyle(t).boxShadow,opacity=getComputedStyle(s).opacity,transform=getComputedStyle(s).transform;t.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt,clientY:box.bottom-2}));const after=getComputedStyle(t).boxShadow;s.dispatchEvent(new DragEvent('dragend',{bubbles:true,dataTransfer:dt}));return {before,after,opacity,transform,cleared:!longtermTasks.querySelector('.card-order-before,.card-order-after,.card-order-dragging')};})()`);
  assert.match(dragStyles.before,/0px 3px 0px 0px inset/);
  assert.match(dragStyles.after,/0px -3px 0px 0px inset/);
  assert.equal(dragStyles.opacity,'0.45'); assert.match(dragStyles.transform,/0\.985/); assert.equal(dragStyles.cleared,true);
  assert.deepEqual(fixture.state.tasks,original);
  assert.equal(await browser.evaluate("calendarGrid.classList.contains('drag-active')"),false);
  await browser.evaluate("closeTaskSummary.click();calendarGrid.querySelector('[data-date=\"2026-09-05\"]').click();openLongtermTasks.click()");
  assert.deepEqual((await titles()).slice(0,3),['持续事项2','持续事项0','持续事项1']);
  await open();assert.deepEqual((await titles()).slice(0,3),['持续事项2','持续事项0','持续事项1']);
  await browser.evaluate("longtermTasks.firstElementChild.querySelector('[data-action=edit]').click();taskText.value='持续事项2改名';taskForm.requestSubmit()");
  await browser.waitFor("taskSummaryDialog.open && longtermTasks.textContent.includes('持续事项2改名')");
  assert.equal((await titles())[0],'持续事项2改名');
  await browser.evaluate("longtermTasks.firstElementChild.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',altKey:true,bubbles:true,cancelable:true}))");
  assert.deepEqual((await titles()).slice(0,2),['持续事项0','持续事项2改名']);
  assert.equal(await browser.evaluate("(()=>{const b=longtermTasks.querySelector('[data-action=edit]');b.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));const e=new DragEvent('dragstart',{bubbles:true,cancelable:true,dataTransfer:new DataTransfer()});b.closest('.task-card').dispatchEvent(e);return e.defaultPrevented})()"),true);
  await browser.evaluate(`(()=>{taskSummaryBody.scrollTop=0;const s=longtermTasks.firstElementChild,dt=new DataTransfer();window.orderDrag={s,dt};s.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));s.dispatchEvent(new DragEvent('dragstart',{bubbles:true,cancelable:true,dataTransfer:dt}));longtermTasks.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt,clientY:taskSummaryBody.getBoundingClientRect().bottom-2}));})()`);
  await browser.waitFor('taskSummaryBody.scrollTop>0');
  await browser.evaluate("orderDrag.s.dispatchEvent(new DragEvent('dragend',{bubbles:true,dataTransfer:orderDrag.dt}));newLongtermTaskButton.click()");
  await browser.waitFor("!taskModal.classList.contains('hidden')");
  assert.equal(await browser.evaluate('taskModalTitle.textContent'),'新增持续工作');
  await browser.evaluate('closeTaskModal.click()');await browser.waitFor('taskSummaryDialog.open');
  assert.equal(await browser.evaluate('document.activeElement===newLongtermTaskButton'),true);
  assert.deepEqual(browser.issues,[]);
});
