import test from 'node:test';
import assert from 'node:assert/strict';
import { browserScenario } from './helpers/browser-scenario.mjs';
import { modelPreferencesFixture } from './helpers/model-preferences-fixture.mjs';

for(const page of ['home','assistant'])test(`${page}模型偏好：独立保存、刷新保留草稿、模型策略及关闭确认`,{timeout:35000},async t=>{
  let api, releaseRefresh;
  t.after(async()=>{releaseRefresh?.();await api?.admin.maintenanceTail;});
  const scenario=await browserScenario(t,{configure:async fixture=>{
    api=await modelPreferencesFixture(fixture.root);
    fixture.state.modelCatalog=await api.command('models.catalog');
    fixture.state.sessionSettings.set('seed',{model:{provider:'p',id:'b'},thinkingLevel:'medium'});
    api.context.emitAgentEvent=event=>{for(const client of fixture.state.eventClients)client.write('data: '+JSON.stringify(event)+'\n\n');};
    fixture.state.modelCommand=async(name,args)=>{const result=await api.command(name,args);fixture.state.modelCatalog=await api.command('models.catalog');return result;};
  }});if(!scenario)return;
  const {browser:b,navigate,fixture}=scenario;
  await b.addInitScript(`const invoke=window.workbench.invoke;window.catalogReads=0;window.workbench.invoke=(id,name,args)=>{if(name==='models.catalog')catalogReads++;return invoke(id,name,args);};`);
  await navigate(page==='home'?'/':'/assistant.html');
  await b.waitFor("modelPickerButton.textContent==='模型 B'");
  const messageSelector=page==='home'?'#chatMessages':'#messages';
  const originalMessages=await b.evaluate(`document.querySelector('${messageSelector}').textContent`);
  if(page==='home'){
    await b.evaluate('homeSettingsButton.click()');await b.waitFor("document.getElementById('homeSettingsHost')?.shadowRoot.getElementById('settingsDialog')?.open");
    await b.evaluate('window.prefRoot=homeSettingsHost.shadowRoot');
  }else{await b.evaluate('settingsButton.click();window.prefRoot=document');}
  await b.evaluate("window.pref=id=>prefRoot.getElementById(id);prefRoot.querySelector('[data-settings-tab=preferences]').click()");
  await b.waitFor("pref('modelPreferencesList').querySelectorAll('.preference-row').length===4");
  assert.deepEqual(await b.evaluate("[...prefRoot.querySelectorAll('[data-settings-tab]')].map(e=>e.textContent)"),['模型配置','模型偏好','项目提示词','技能管理','阅读设置','自定义模型（高级）']);
  assert.equal(api.state.networkCalls,0);
  const checked=key=>b.evaluate(`pref('modelPreferencesList').querySelector('[data-model-key="${key}"] input').checked`);
  const toggle=key=>b.evaluate(`pref('modelPreferencesList').querySelector('[data-model-key="${key}"] input').click()`);
  assert.equal(await b.evaluate("pref('modelPreferencesList').querySelector('[data-model-key=\"p/a\"] input').disabled"),true);
  await toggle('p/b');
  await b.evaluate("pref('defaultModelSelect').value='q/c';pref('defaultModelSelect').dispatchEvent(new Event('change'))");
  assert.deepEqual(await b.evaluate("[...pref('defaultThinking').options].map(o=>o.value)"),['off']);
  const initialReads=await b.evaluate('catalogReads');
  await b.evaluate("pref('saveModelDisplay').click()");await b.waitFor("pref('saveModelDisplay').disabled&&!pref('refreshModelCatalog').disabled");
  assert.equal(await b.evaluate('catalogReads'),initialReads,'操作结果及目录事件不应触发重复读取');
  assert.deepEqual((await api.readPreferences()).enabledModels,['p/a','q/c']);assert.equal((await api.readPreferences()).defaultModel,'a');
  assert.equal(await b.evaluate("pref('defaultModelSelect').value"),'q/c');assert.equal(await b.evaluate("pref('saveModelDefaults').disabled"),false);
  assert.equal(await b.evaluate('modelPickerButton.textContent'),'模型 B');
  await toggle('p/d');
  api.state.remote=[...api.state.models,api.model('p','e')];api.state.failures.add('q');
  const oldPrefs=await api.readPreferences();
  api.state.refreshGate=new Promise(resolve=>{releaseRefresh=resolve;});
  await b.evaluate("pref('refreshModelCatalog').click()");await b.waitFor("pref('modelRefreshStatus').textContent==='正在处理…'");
  assert.equal(await checked('p/d'),true);assert.equal(await b.evaluate("pref('defaultModelSelect').value"),'q/c');
  assert.equal(await b.evaluate("pref('modelPreferencesList').querySelectorAll('.preference-row').length"),4);
  releaseRefresh();api.state.refreshGate=null;
  await b.waitFor("pref('modelRefreshStatus').textContent.includes('部分')&&!pref('refreshModelCatalog').disabled");
  assert.equal(await checked('p/d'),true);assert.equal(await checked('p/e'),false);assert.equal(await b.evaluate("pref('defaultModelSelect').value"),'q/c');
  assert.equal(await b.evaluate("pref('modelPreferencesList').querySelector('[data-model-key=\"p/e\"] .model-new-badge').textContent"),'新增');
  assert.ok(await b.evaluate("pref('modelRefreshTime').textContent!=='最近成功更新：暂无'&&pref('modelRefreshResults').textContent.includes('q 模拟目录不可用')"));
  assert.deepEqual(await api.readPreferences(),oldPrefs);
  assert.equal(await b.evaluate("[...pref('defaultModelSelect').options].some(o=>o.value==='p/d')"),false,'未保存的显示勾选不进入默认模型候选');
  await b.evaluate("pref('saveModelDefaults').click()");await b.waitFor("pref('saveModelDefaults').disabled&&!pref('refreshModelCatalog').disabled");
  assert.equal((await api.readPreferences()).defaultModel,'c');assert.deepEqual((await api.readPreferences()).enabledModels,['p/a','q/c']);
  assert.equal(await checked('p/d'),true);assert.equal(await b.evaluate("pref('saveModelDisplay').disabled"),false);
  // Both close and tab-switch ask before discarding the remaining display draft.
  await b.evaluate("pref('closeSettings').click()");await b.waitFor("pref('uiDialog').open");await b.evaluate("pref('uiDialogCancel').click()");await b.waitFor("!pref('uiDialog').open");
  assert.equal(await checked('p/d'),true);
  await b.evaluate("prefRoot.querySelector('[data-settings-tab=custom]').click()");await b.waitFor("pref('uiDialog').open");await b.evaluate("pref('uiDialogConfirm').click()");
  await b.waitFor("pref('customTab').classList.contains('active')");
  await b.evaluate("prefRoot.querySelector('[data-settings-tab=preferences]').click()");await b.waitFor("pref('preferencesTab').classList.contains('active')&&pref('saveModelDisplay').disabled");
  assert.equal(await checked('p/d'),false);
  await b.evaluate("pref('selectAllModels').click();pref('saveModelDisplay').click()");await b.waitFor("pref('saveModelDisplay').disabled&&!pref('refreshModelCatalog').disabled");
  assert.deepEqual((await api.readPreferences()).enabledModels,[]);
  api.state.failures.clear();api.state.remote=[...api.state.models,api.model('p','f')];
  await b.evaluate("pref('refreshModelCatalog').click()");await b.waitFor("pref('modelPreferencesList').querySelector('[data-model-key=\"p/f\"]')&&!pref('refreshModelCatalog').disabled");
  assert.equal(await checked('p/f'),true);assert.equal(await b.evaluate("pref('saveModelDisplay').disabled"),true);
  await b.evaluate("pref('modelPreferencesSearch').value='q';pref('modelPreferencesSearch').dispatchEvent(new Event('input'))");
  assert.equal(await b.evaluate("pref('modelPreferencesList').querySelectorAll('.preference-row').length"),1);
  await b.evaluate("pref('modelPreferencesSearch').value='';pref('modelPreferencesSearch').dispatchEvent(new Event('input'))");
  const rows=await b.evaluate("pref('modelPreferencesList').textContent"),time=await b.evaluate("pref('modelRefreshTime').textContent");
  api.state.failures.add('p');api.state.failures.add('q');
  await b.evaluate("pref('refreshModelCatalog').click()");await b.waitFor("pref('modelRefreshStatus').textContent==='刷新失败'&&!pref('refreshModelCatalog').disabled");
  assert.equal(await b.evaluate("pref('modelPreferencesList').textContent"),rows);assert.equal(await b.evaluate("pref('modelRefreshTime').textContent"),time);
  await b.evaluate("pref('defaultModelSelect').value='p/d';pref('defaultModelSelect').dispatchEvent(new Event('change'));pref('defaultThinking').value='high';pref('defaultThinking').dispatchEvent(new Event('change'));pref('closeSettings').click()");
  await b.waitFor("pref('uiDialog').open");await b.evaluate("pref('uiDialogCancel').click()");await b.waitFor("!pref('uiDialog').open");
  api.state.failures.clear();api.state.remote=api.state.models.map(m=>m.id==='d'?{...m,reasoning:false,thinkingLevels:['off']}:m);
  await b.evaluate("pref('refreshModelCatalog').click()");await b.waitFor("!pref('refreshModelCatalog').disabled&&pref('modelRefreshStatus').textContent==='刷新成功'");
  assert.equal(await b.evaluate("pref('defaultModelSelect').value"),'p/d');assert.equal(await b.evaluate("pref('defaultThinking').value"),'high','能力变化也保留未保存草稿');
  assert.deepEqual(await b.evaluate("[...pref('defaultThinking').options].filter(o=>!o.disabled).map(o=>o.value)"),['off']);
  const writes=api.state.writes.length;await b.evaluate("pref('saveModelDefaults').click()");assert.equal(api.state.writes.length,writes);
  await b.evaluate("pref('defaultThinking').value='off';pref('defaultThinking').dispatchEvent(new Event('change'));pref('saveModelDefaults').click()");await b.waitFor("pref('saveModelDefaults').disabled&&!pref('refreshModelCatalog').disabled");
  assert.equal(api.state.networkCalls,4);
  assert.equal(fixture.state.sessionSettings.get('seed').model.id,'b');assert.equal(await b.evaluate('modelPickerButton.textContent'),'模型 B');
  assert.equal(await b.evaluate(`document.querySelector('${messageSelector}').textContent`),originalMessages);assert.equal(api.state.stopCalls,0);
  assert.deepEqual(b.issues,[]);
});
