export function createHomeState(today) {
  return {
    planner: {
      today,
      selectedDate: today,
      month: today.slice(0, 7),
      dashboard: null,
      sourceRevision: null,
      taskById: new Map(),
      editingTaskId: null,
      datePickerField: null,
      datePickerMonth: null,
      taskSaving: false,
      draggedTaskId: null,
      dragSourceDate: null,
      dashboardRequest: 0,
      dayRequest: 0,
    },
    chat: {
      chatBusy: false,
      activeSessionId: null,
      activeSessionPath: null,
      liveAssistant: null,
      liveText: "",
      historyTab: "sessions",
      historyItems: [],
      historyBusy: false,
      historyRequest: 0,
      workspace: null,
      workspaceReloadTimer: null,
    },
    records: {
      activeTab: "tasks",
      taskCount: 0,
      recordCount: 0,
      selectedDate: today,
      records: [],
      displayRecords: [],
      recordById: new Map(),
      monthCounts: new Map(),
      expandedIds: new Set(),
      searchQuery: "",
      dayRequest: 0,
      monthRequest: 0,
      searchRequest: 0,
      saving: false,
      editingRecord: null,
      editorInitial: "",
      editorSaving: false,
    },
    vskills: {
      vskills: [],
      vskillBusy: false,
      vskillEditingId: null,
    },
  };
}
